use_small_heuristics = "Max"
newline_style = "Unix"
tab_spaces = 3
# When in stable, change to granularity.
# unstable_features = true
# merge_imports = true
# imports_granularity = "Crate"
edition = "2024"
